### ISSUE TITLE
Song title typos

### ISSUE THREAD

**Issue by LightningLand** [vegdev/fantasy-football#1]
Old Torornto = Old Toronto

Golden Audo Mile = Golden Auto Mile

<img width="191" alt="Screen Shot 2023-01-04 at 2 01 29 PM" src="https://user-images.githubusercontent.com/121973199/210629788-6ebfcfe7-c865-43b2-8b97-e804a3056370.png">

**Comment by vegdev** [comment]
Issue resolved, typo fixed.
