### ISSUE TITLE
Playback buttons

### ISSUE THREAD

**Issue by LightningLand** [vegdev/fantasy-football#2]
- Stop button showing as incorrect image in Chrome browser.

<img width="67" alt="Screen Shot 2023-01-04 at 2 04 54 PM" src="https://user-images.githubusercontent.com/121973199/210630363-28f60707-98cd-4dbf-bf07-f1bf7a93ff9f.png">

- Cursor changing to text cursor on hover

**Comment by vegdev** [comment]
Also to add more controls such as pause, volume and duration slider

**Comment by LightningLand** [comment]
Playback buttons are displaying correctly - and Issue #9 addresses remaining concerns.
