### ISSUE TITLE
Mobile playback

### ISSUE THREAD

**Issue by LightningLand** [vegdev/fantasy-football#3]
- Mobile playback inconsistent
- When it does play:
- songs stop when browser minimized
- Continuous play doesn't always work

**Comment by vegdev** [comment]
plays fine on my samsung
doesnt play at all on my iphone

May need to add support for other audio formats such as ogg.
also looking into other solutions: `HTML5 Audio pool` , `Howler.mobileAutoEnable`

Audio halting when browser moves to background could be browser or device specific, I have been unable to reproduce this issue so far.

**Comment by vegdev** [comment]
believe this is mostly solved with commit 33996f2e3f652f758b7a9cb892d4a44163e0161c
