### ISSUE TITLE
Player auto-size

### ISSUE THREAD

**Issue by LightningLand** [vegdev/fantasy-football#4]
Too much gray space at bottom of player.

<img width="437" alt="Screen Shot 2023-01-04 at 2 08 20 PM" src="https://user-images.githubusercontent.com/121973199/210630839-d7a875e4-0d50-40a9-9aad-cd07c52c0540.png">

**Comment by vegdev** [comment]
Resolved in commit 8fe7d35fdf681ad61225ed4dfa5332563f9aaa0d
