### ISSUE TITLE
Song versions

### ISSUE THREAD

**Issue by LightningLand** [vegdev/fantasy-football#6]
New Song versions are .wav files in Google Drive: Fantasy Football > Lightning Land > MASTERS.

REMOVE Flesh of the Gods from the entire album.

**Comment by vegdev** [comment]
resolved with commit cbb661168b7e616db4e908ecf23864099e8a050d although wav files are 10X larger than mp3 and we will see if the affect to page load is worth it

**Comment by LightningLand** [comment]
MP3 versions of latest masters are .mp3 files in Google Drive: Fantasy Football > Lightning Land > MASTERS > MP3
