### ISSUE TITLE
Castles Made of Sand New Version 01/11/23

### ISSUE THREAD

**Issue by LightningLand** [vegdev/fantasy-football#7]
Re-mastered version of 7. Castles Made of Sand has been uploaded to the [MASTERS > MP3 ](https://drive.google.com/drive/folders/1e_-cxkMiSPkS2cKW4H3k-6JgS7l5jUsb) folder for upload. Muchos gracias por favor.

**Comment by vegdev** [comment]
issue resolved with commit c8925569e38a7bdfb035b536663884144f91d91b
