### ISSUE TITLE
Add LIGHTNING LAND title

### ISSUE THREAD

**Issue by LightningLand** [vegdev/fantasy-football#8]
Above 1. Old Toronto within the player window, add LIGHTNING LAND album title in caps, same font size as the song titles.

**Comment by LightningLand** [comment]
![Group 30](https://user-images.githubusercontent.com/121973199/212135461-ceebbce2-83c2-4c61-8881-0ed5abb9426b.png)

**Comment by vegdev** [comment]
ticket resolved in commit 10534c606f96d42d15d16378a83460836e5dbd21
